name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "25 8 * * *"   # 1:55 PM IST daily

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Workflow triggered at $(date) by ${{ github.event_name }}"
